using System.ComponentModel;

namespace MauiIcons.FontAwesome.Solid;

public enum FontAwesomeSolidIcons
{
    [Description("\u0030")]
    Zero,
    [Description("\u0031")]
    One,
    [Description("\u0032")]
    Two,
    [Description("\u0033")]
    Three,
    [Description("\u0034")]
    Four,
    [Description("\u0035")]
    Five,
    [Description("\u0036")]
    Six,
    [Description("\u0037")]
    Seven,
    [Description("\u0038")]
    Eight,
    [Description("\u0039")]
    Nine,
    [Description("\u0041")]
    A,
    [Description("\uf2b9")]
    AddressBook,
    [Description("\uf2bb")]
    AddressCard,
    [Description("\uf34e")]
    AlarmClock,
    [Description("\uf037")]
    AlignCenter,
    [Description("\uf039")]
    AlignJustify,
    [Description("\uf036")]
    AlignLeft,
    [Description("\uf038")]
    AlignRight,
    [Description("\uf13d")]
    Anchor,
    [Description("\ue4aa")]
    AnchorCircleCheck,
    [Description("\ue4ab")]
    AnchorCircleExclamation,
    [Description("\ue4ac")]
    AnchorCircleXmark,
    [Description("\ue4ad")]
    AnchorLock,
    [Description("\uf107")]
    AngleDown,
    [Description("\uf104")]
    AngleLeft,
    [Description("\uf105")]
    AngleRight,
    [Description("\uf106")]
    AngleUp,
    [Description("\uf103")]
    AnglesDown,
    [Description("\uf100")]
    AnglesLeft,
    [Description("\uf101")]
    AnglesRight,
    [Description("\uf102")]
    AnglesUp,
    [Description("\uf644")]
    Ankh,
    [Description("\uf5d1")]
    AppleWhole,
    [Description("\ue845")]
    Aquarius,
    [Description("\uf557")]
    Archway,
    [Description("\ue846")]
    Aries,
    [Description("\uf063")]
    ArrowDown,
    [Description("\uf162")]
    ArrowDown19,
    [Description("\uf886")]
    ArrowDown91,
    [Description("\uf15d")]
    ArrowDownAZ,
    [Description("\uf175")]
    ArrowDownLong,
    [Description("\uf884")]
    ArrowDownShortWide,
    [Description("\ue4af")]
    ArrowDownUpAcrossLine,
    [Description("\ue4b0")]
    ArrowDownUpLock,
    [Description("\uf160")]
    ArrowDownWideShort,
    [Description("\uf881")]
    ArrowDownZA,
    [Description("\uf060")]
    ArrowLeft,
    [Description("\uf177")]
    ArrowLeftLong,
    [Description("\uf245")]
    ArrowPointer,
    [Description("\uf061")]
    ArrowRight,
    [Description("\uf0ec")]
    ArrowRightArrowLeft,
    [Description("\uf08b")]
    ArrowRightFromBracket,
    [Description("\uf178")]
    ArrowRightLong,
    [Description("\uf090")]
    ArrowRightToBracket,
    [Description("\ue4b3")]
    ArrowRightToCity,
    [Description("\uf0e2")]
    ArrowRotateLeft,
    [Description("\uf01e")]
    ArrowRotateRight,
    [Description("\ue097")]
    ArrowTrendDown,
    [Description("\ue098")]
    ArrowTrendUp,
    [Description("\uf149")]
    ArrowTurnDown,
    [Description("\uf148")]
    ArrowTurnUp,
    [Description("\uf062")]
    ArrowUp,
    [Description("\uf163")]
    ArrowUp19,
    [Description("\uf887")]
    ArrowUp91,
    [Description("\uf15e")]
    ArrowUpAZ,
    [Description("\ue09a")]
    ArrowUpFromBracket,
    [Description("\ue4b5")]
    ArrowUpFromGroundWater,
    [Description("\ue4b6")]
    ArrowUpFromWaterPump,
    [Description("\uf176")]
    ArrowUpLong,
    [Description("\ue4b7")]
    ArrowUpRightDots,
    [Description("\uf08e")]
    ArrowUpRightFromSquare,
    [Description("\uf885")]
    ArrowUpShortWide,
    [Description("\uf161")]
    ArrowUpWideShort,
    [Description("\uf882")]
    ArrowUpZA,
    [Description("\ue4b8")]
    ArrowsDownToLine,
    [Description("\ue4b9")]
    ArrowsDownToPeople,
    [Description("\uf07e")]
    ArrowsLeftRight,
    [Description("\ue4ba")]
    ArrowsLeftRightToLine,
    [Description("\uf021")]
    ArrowsRotate,
    [Description("\ue4bb")]
    ArrowsSpin,
    [Description("\ue4bc")]
    ArrowsSplitUpAndLeft,
    [Description("\ue4bd")]
    ArrowsToCircle,
    [Description("\ue4be")]
    ArrowsToDot,
    [Description("\ue4bf")]
    ArrowsToEye,
    [Description("\ue4c0")]
    ArrowsTurnRight,
    [Description("\ue4c1")]
    ArrowsTurnToDots,
    [Description("\uf07d")]
    ArrowsUpDown,
    [Description("\uf047")]
    ArrowsUpDownLeftRight,
    [Description("\ue4c2")]
    ArrowsUpToLine,
    [Description("\u002a")]
    Asterisk,
    [Description("\u0040")]
    At,
    [Description("\uf5d2")]
    Atom,
    [Description("\uf29e")]
    AudioDescription,
    [Description("\ue0a9")]
    AustralSign,
    [Description("\uf559")]
    Award,
    [Description("\u0042")]
    B,
    [Description("\uf77c")]
    Baby,
    [Description("\uf77d")]
    BabyCarriage,
    [Description("\uf04a")]
    Backward,
    [Description("\uf049")]
    BackwardFast,
    [Description("\uf048")]
    BackwardStep,
    [Description("\uf7e5")]
    Bacon,
    [Description("\ue059")]
    Bacteria,
    [Description("\ue05a")]
    Bacterium,
    [Description("\uf290")]
    BagShopping,
    [Description("\uf666")]
    Bahai,
    [Description("\ue0ac")]
    BahtSign,
    [Description("\uf05e")]
    Ban,
    [Description("\uf54d")]
    BanSmoking,
    [Description("\uf462")]
    Bandage,
    [Description("\ue2e6")]
    BangladeshiTakaSign,
    [Description("\uf02a")]
    Barcode,
    [Description("\uf0c9")]
    Bars,
    [Description("\uf828")]
    BarsProgress,
    [Description("\uf550")]
    BarsStaggered,
    [Description("\uf433")]
    Baseball,
    [Description("\uf432")]
    BaseballBatBall,
    [Description("\uf291")]
    BasketShopping,
    [Description("\uf434")]
    Basketball,
    [Description("\uf2cd")]
    Bath,
    [Description("\uf244")]
    BatteryEmpty,
    [Description("\uf240")]
    BatteryFull,
    [Description("\uf242")]
    BatteryHalf,
    [Description("\uf243")]
    BatteryQuarter,
    [Description("\uf241")]
    BatteryThreeQuarters,
    [Description("\uf236")]
    Bed,
    [Description("\uf487")]
    BedPulse,
    [Description("\uf0fc")]
    BeerMugEmpty,
    [Description("\uf0f3")]
    Bell,
    [Description("\uf562")]
    BellConcierge,
    [Description("\uf1f6")]
    BellSlash,
    [Description("\uf55b")]
    BezierCurve,
    [Description("\uf206")]
    Bicycle,
    [Description("\uf1e5")]
    Binoculars,
    [Description("\uf780")]
    Biohazard,
    [Description("\ue0b4")]
    BitcoinSign,
    [Description("\uf517")]
    Blender,
    [Description("\uf6b6")]
    BlenderPhone,
    [Description("\uf781")]
    Blog,
    [Description("\uf032")]
    Bold,
    [Description("\uf0e7")]
    Bolt,
    [Description("\ue0b7")]
    BoltLightning,
    [Description("\uf1e2")]
    Bomb,
    [Description("\uf5d7")]
    Bone,
    [Description("\uf55c")]
    Bong,
    [Description("\uf02d")]
    Book,
    [Description("\uf558")]
    BookAtlas,
    [Description("\uf647")]
    BookBible,
    [Description("\ue0bb")]
    BookBookmark,
    [Description("\uf66a")]
    BookJournalWhills,
    [Description("\uf7e6")]
    BookMedical,
    [Description("\uf518")]
    BookOpen,
    [Description("\uf5da")]
    BookOpenReader,
    [Description("\uf687")]
    BookQuran,
    [Description("\uf6b7")]
    BookSkull,
    [Description("\uf827")]
    BookTanakh,
    [Description("\uf02e")]
    Bookmark,
    [Description("\uf84c")]
    BorderAll,
    [Description("\uf850")]
    BorderNone,
    [Description("\uf853")]
    BorderTopLeft,
    [Description("\ue4c3")]
    BoreHole,
    [Description("\ue4c4")]
    BottleDroplet,
    [Description("\ue4c5")]
    BottleWater,
    [Description("\ue4c6")]
    BowlFood,
    [Description("\ue2eb")]
    BowlRice,
    [Description("\uf436")]
    BowlingBall,
    [Description("\uf466")]
    Box,
    [Description("\uf187")]
    BoxArchive,
    [Description("\uf49e")]
    BoxOpen,
    [Description("\ue05b")]
    BoxTissue,
    [Description("\ue4c7")]
    BoxesPacking,
    [Description("\uf468")]
    BoxesStacked,
    [Description("\uf2a1")]
    Braille,
    [Description("\uf5dc")]
    Brain,
    [Description("\ue46c")]
    BrazilianRealSign,
    [Description("\uf7ec")]
    BreadSlice,
    [Description("\ue4c8")]
    Bridge,
    [Description("\ue4c9")]
    BridgeCircleCheck,
    [Description("\ue4ca")]
    BridgeCircleExclamation,
    [Description("\ue4cb")]
    BridgeCircleXmark,
    [Description("\ue4cc")]
    BridgeLock,
    [Description("\ue4ce")]
    BridgeWater,
    [Description("\uf0b1")]
    Briefcase,
    [Description("\uf469")]
    BriefcaseMedical,
    [Description("\uf51a")]
    Broom,
    [Description("\uf458")]
    BroomBall,
    [Description("\uf55d")]
    Brush,
    [Description("\ue4cf")]
    Bucket,
    [Description("\uf188")]
    Bug,
    [Description("\ue490")]
    BugSlash,
    [Description("\ue4d0")]
    Bugs,
    [Description("\uf1ad")]
    Building,
    [Description("\ue4d1")]
    BuildingCircleArrowRight,
    [Description("\ue4d2")]
    BuildingCircleCheck,
    [Description("\ue4d3")]
    BuildingCircleExclamation,
    [Description("\ue4d4")]
    BuildingCircleXmark,
    [Description("\uf19c")]
    BuildingColumns,
    [Description("\ue4d5")]
    BuildingFlag,
    [Description("\ue4d6")]
    BuildingLock,
    [Description("\ue4d7")]
    BuildingNgo,
    [Description("\ue4d8")]
    BuildingShield,
    [Description("\ue4d9")]
    BuildingUn,
    [Description("\ue4da")]
    BuildingUser,
    [Description("\ue4db")]
    BuildingWheat,
    [Description("\uf0a1")]
    Bullhorn,
    [Description("\uf140")]
    Bullseye,
    [Description("\uf805")]
    Burger,
    [Description("\ue4dc")]
    Burst,
    [Description("\uf207")]
    Bus,
    [Description("\ue81d")]
    BusSide,
    [Description("\uf55e")]
    BusSimple,
    [Description("\uf64a")]
    BusinessTime,
    [Description("\u0043")]
    C,
    [Description("\uf7da")]
    CableCar,
    [Description("\uf1fd")]
    CakeCandles,
    [Description("\uf1ec")]
    Calculator,
    [Description("\uf133")]
    Calendar,
    [Description("\uf274")]
    CalendarCheck,
    [Description("\uf783")]
    CalendarDay,
    [Description("\uf073")]
    CalendarDays,
    [Description("\uf272")]
    CalendarMinus,
    [Description("\uf271")]
    CalendarPlus,
    [Description("\uf784")]
    CalendarWeek,
    [Description("\uf273")]
    CalendarXmark,
    [Description("\uf030")]
    Camera,
    [Description("\uf083")]
    CameraRetro,
    [Description("\ue0d8")]
    CameraRotate,
    [Description("\uf6bb")]
    Campground,
    [Description("\ue847")]
    Cancer,
    [Description("\uf786")]
    CandyCane,
    [Description("\uf55f")]
    Cannabis,
    [Description("\ue848")]
    Capricorn,
    [Description("\uf46b")]
    Capsules,
    [Description("\uf1b9")]
    Car,
    [Description("\uf5df")]
    CarBattery,
    [Description("\uf5e1")]
    CarBurst,
    [Description("\ue4dd")]
    CarOn,
    [Description("\uf5de")]
    CarRear,
    [Description("\uf5e4")]
    CarSide,
    [Description("\ue4de")]
    CarTunnel,
    [Description("\uf8ff")]
    Caravan,
    [Description("\uf0d7")]
    CaretDown,
    [Description("\uf0d9")]
    CaretLeft,
    [Description("\uf0da")]
    CaretRight,
    [Description("\uf0d8")]
    CaretUp,
    [Description("\uf787")]
    Carrot,
    [Description("\uf218")]
    CartArrowDown,
    [Description("\uf474")]
    CartFlatbed,
    [Description("\uf59d")]
    CartFlatbedSuitcase,
    [Description("\uf217")]
    CartPlus,
    [Description("\uf07a")]
    CartShopping,
    [Description("\uf788")]
    CashRegister,
    [Description("\uf6be")]
    Cat,
    [Description("\ue0df")]
    CediSign,
    [Description("\ue3f5")]
    CentSign,
    [Description("\uf0a3")]
    Certificate,
    [Description("\uf6c0")]
    Chair,
    [Description("\uf51b")]
    Chalkboard,
    [Description("\uf51c")]
    ChalkboardUser,
    [Description("\uf79f")]
    ChampagneGlasses,
    [Description("\uf5e7")]
    ChargingStation,
    [Description("\uf1fe")]
    ChartArea,
    [Description("\uf080")]
    ChartBar,
    [Description("\ue0e3")]
    ChartColumn,
    [Description("\ue695")]
    ChartDiagram,
    [Description("\ue0e4")]
    ChartGantt,
    [Description("\uf201")]
    ChartLine,
    [Description("\uf200")]
    ChartPie,
    [Description("\ue473")]
    ChartSimple,
    [Description("\uf00c")]
    Check,
    [Description("\uf560")]
    CheckDouble,
    [Description("\uf772")]
    CheckToSlot,
    [Description("\uf7ef")]
    Cheese,
    [Description("\uf439")]
    Chess,
    [Description("\uf43a")]
    ChessBishop,
    [Description("\uf43c")]
    ChessBoard,
    [Description("\uf43f")]
    ChessKing,
    [Description("\uf441")]
    ChessKnight,
    [Description("\uf443")]
    ChessPawn,
    [Description("\uf445")]
    ChessQueen,
    [Description("\uf447")]
    ChessRook,
    [Description("\uf078")]
    ChevronDown,
    [Description("\uf053")]
    ChevronLeft,
    [Description("\uf054")]
    ChevronRight,
    [Description("\uf077")]
    ChevronUp,
    [Description("\uf1ae")]
    Child,
    [Description("\ue4e0")]
    ChildCombatant,
    [Description("\ue59c")]
    ChildDress,
    [Description("\ue59d")]
    ChildReaching,
    [Description("\ue4e1")]
    Children,
    [Description("\uf51d")]
    Church,
    [Description("\uf111")]
    Circle,
    [Description("\uf0ab")]
    CircleArrowDown,
    [Description("\uf0a8")]
    CircleArrowLeft,
    [Description("\uf0a9")]
    CircleArrowRight,
    [Description("\uf0aa")]
    CircleArrowUp,
    [Description("\uf058")]
    CircleCheck,
    [Description("\uf13a")]
    CircleChevronDown,
    [Description("\uf137")]
    CircleChevronLeft,
    [Description("\uf138")]
    CircleChevronRight,
    [Description("\uf139")]
    CircleChevronUp,
    [Description("\uf4b9")]
    CircleDollarToSlot,
    [Description("\uf192")]
    CircleDot,
    [Description("\uf358")]
    CircleDown,
    [Description("\uf06a")]
    CircleExclamation,
    [Description("\uf47e")]
    CircleH,
    [Description("\uf042")]
    CircleHalfStroke,
    [Description("\uf05a")]
    CircleInfo,
    [Description("\uf359")]
    CircleLeft,
    [Description("\uf056")]
    CircleMinus,
    [Description("\ue4e2")]
    CircleNodes,
    [Description("\uf1ce")]
    CircleNotch,
    [Description("\uf28b")]
    CirclePause,
    [Description("\uf144")]
    CirclePlay,
    [Description("\uf055")]
    CirclePlus,
    [Description("\uf059")]
    CircleQuestion,
    [Description("\uf7ba")]
    CircleRadiation,
    [Description("\uf35a")]
    CircleRight,
    [Description("\uf28d")]
    CircleStop,
    [Description("\uf35b")]
    CircleUp,
    [Description("\uf2bd")]
    CircleUser,
    [Description("\uf057")]
    CircleXmark,
    [Description("\uf64f")]
    City,
    [Description("\ue131")]
    Clapperboard,
    [Description("\uf328")]
    Clipboard,
    [Description("\uf46c")]
    ClipboardCheck,
    [Description("\uf46d")]
    ClipboardList,
    [Description("\ue4e3")]
    ClipboardQuestion,
    [Description("\uf7f3")]
    ClipboardUser,
    [Description("\uf017")]
    Clock,
    [Description("\uf1da")]
    ClockRotateLeft,
    [Description("\uf24d")]
    Clone,
    [Description("\uf20a")]
    ClosedCaptioning,
    [Description("\ue135")]
    ClosedCaptioningSlash,
    [Description("\uf0c2")]
    Cloud,
    [Description("\uf0ed")]
    CloudArrowDown,
    [Description("\uf0ee")]
    CloudArrowUp,
    [Description("\uf76c")]
    CloudBolt,
    [Description("\uf73b")]
    CloudMeatball,
    [Description("\uf6c3")]
    CloudMoon,
    [Description("\uf73c")]
    CloudMoonRain,
    [Description("\uf73d")]
    CloudRain,
    [Description("\uf740")]
    CloudShowersHeavy,
    [Description("\ue4e4")]
    CloudShowersWater,
    [Description("\uf6c4")]
    CloudSun,
    [Description("\uf743")]
    CloudSunRain,
    [Description("\ue139")]
    Clover,
    [Description("\uf121")]
    Code,
    [Description("\uf126")]
    CodeBranch,
    [Description("\uf386")]
    CodeCommit,
    [Description("\ue13a")]
    CodeCompare,
    [Description("\ue13b")]
    CodeFork,
    [Description("\uf387")]
    CodeMerge,
    [Description("\ue13c")]
    CodePullRequest,
    [Description("\uf51e")]
    Coins,
    [Description("\ue140")]
    ColonSign,
    [Description("\uf075")]
    Comment,
    [Description("\uf651")]
    CommentDollar,
    [Description("\uf4ad")]
    CommentDots,
    [Description("\uf7f5")]
    CommentMedical,
    [Description("\ue696")]
    CommentNodes,
    [Description("\uf4b3")]
    CommentSlash,
    [Description("\uf7cd")]
    CommentSms,
    [Description("\uf086")]
    Comments,
    [Description("\uf653")]
    CommentsDollar,
    [Description("\uf51f")]
    CompactDisc,
    [Description("\uf14e")]
    Compass,
    [Description("\uf568")]
    CompassDrafting,
    [Description("\uf066")]
    Compress,
    [Description("\ue4e5")]
    Computer,
    [Description("\uf8cc")]
    ComputerMouse,
    [Description("\uf563")]
    Cookie,
    [Description("\uf564")]
    CookieBite,
    [Description("\uf0c5")]
    Copy,
    [Description("\uf1f9")]
    Copyright,
    [Description("\uf4b8")]
    Couch,
    [Description("\uf6c8")]
    Cow,
    [Description("\uf09d")]
    CreditCard,
    [Description("\uf125")]
    Crop,
    [Description("\uf565")]
    CropSimple,
    [Description("\uf654")]
    Cross,
    [Description("\uf05b")]
    Crosshairs,
    [Description("\uf520")]
    Crow,
    [Description("\uf521")]
    Crown,
    [Description("\uf7f7")]
    Crutch,
    [Description("\ue152")]
    CruzeiroSign,
    [Description("\uf1b2")]
    Cube,
    [Description("\uf1b3")]
    Cubes,
    [Description("\ue4e6")]
    CubesStacked,
    [Description("\u0044")]
    D,
    [Description("\uf1c0")]
    Database,
    [Description("\uf55a")]
    DeleteLeft,
    [Description("\uf747")]
    Democrat,
    [Description("\uf390")]
    Desktop,
    [Description("\uf655")]
    Dharmachakra,
    [Description("\ue476")]
    DiagramNext,
    [Description("\ue477")]
    DiagramPredecessor,
    [Description("\uf542")]
    DiagramProject,
    [Description("\ue47a")]
    DiagramSuccessor,
    [Description("\uf219")]
    Diamond,
    [Description("\uf5eb")]
    DiamondTurnRight,
    [Description("\uf522")]
    Dice,
    [Description("\uf6cf")]
    DiceD20,
    [Description("\uf6d1")]
    DiceD6,
    [Description("\uf523")]
    DiceFive,
    [Description("\uf524")]
    DiceFour,
    [Description("\uf525")]
    DiceOne,
    [Description("\uf526")]
    DiceSix,
    [Description("\uf527")]
    DiceThree,
    [Description("\uf528")]
    DiceTwo,
    [Description("\uf7fa")]
    Disease,
    [Description("\ue163")]
    Display,
    [Description("\uf529")]
    Divide,
    [Description("\uf471")]
    Dna,
    [Description("\uf6d3")]
    Dog,
    [Description("\u0024")]
    DollarSign,
    [Description("\uf472")]
    Dolly,
    [Description("\ue169")]
    DongSign,
    [Description("\uf52a")]
    DoorClosed,
    [Description("\uf52b")]
    DoorOpen,
    [Description("\uf4ba")]
    Dove,
    [Description("\uf422")]
    DownLeftAndUpRightToCenter,
    [Description("\uf309")]
    DownLong,
    [Description("\uf019")]
    Download,
    [Description("\uf6d5")]
    Dragon,
    [Description("\uf5ee")]
    DrawPolygon,
    [Description("\uf043")]
    Droplet,
    [Description("\uf5c7")]
    DropletSlash,
    [Description("\uf569")]
    Drum,
    [Description("\uf56a")]
    DrumSteelpan,
    [Description("\uf6d7")]
    DrumstickBite,
    [Description("\uf44b")]
    Dumbbell,
    [Description("\uf793")]
    Dumpster,
    [Description("\uf794")]
    DumpsterFire,
    [Description("\uf6d9")]
    Dungeon,
    [Description("\u0045")]
    E,
    [Description("\uf2a4")]
    EarDeaf,
    [Description("\uf2a2")]
    EarListen,
    [Description("\uf57c")]
    EarthAfrica,
    [Description("\uf57d")]
    EarthAmericas,
    [Description("\uf57e")]
    EarthAsia,
    [Description("\uf7a2")]
    EarthEurope,
    [Description("\ue47b")]
    EarthOceania,
    [Description("\uf7fb")]
    Egg,
    [Description("\uf052")]
    Eject,
    [Description("\ue16d")]
    Elevator,
    [Description("\uf141")]
    Ellipsis,
    [Description("\uf142")]
    EllipsisVertical,
    [Description("\uf0e0")]
    Envelope,
    [Description("\ue4e8")]
    EnvelopeCircleCheck,
    [Description("\uf2b6")]
    EnvelopeOpen,
    [Description("\uf658")]
    EnvelopeOpenText,
    [Description("\uf674")]
    EnvelopesBulk,
    [Description("\u003d")]
    Equals,
    [Description("\uf12d")]
    Eraser,
    [Description("\uf796")]
    Ethernet,
    [Description("\uf153")]
    EuroSign,
    [Description("\u0021")]
    Exclamation,
    [Description("\uf065")]
    Expand,
    [Description("\ue4e9")]
    Explosion,
    [Description("\uf06e")]
    Eye,
    [Description("\uf1fb")]
    EyeDropper,
    [Description("\uf2a8")]
    EyeLowVision,
    [Description("\uf070")]
    EyeSlash,
    [Description("\u0046")]
    F,
    [Description("\uf556")]
    FaceAngry,
    [Description("\uf567")]
    FaceDizzy,
    [Description("\uf579")]
    FaceFlushed,
    [Description("\uf119")]
    FaceFrown,
    [Description("\uf57a")]
    FaceFrownOpen,
    [Description("\uf57f")]
    FaceGrimace,
    [Description("\uf580")]
    FaceGrin,
    [Description("\uf582")]
    FaceGrinBeam,
    [Description("\uf583")]
    FaceGrinBeamSweat,
    [Description("\uf584")]
    FaceGrinHearts,
    [Description("\uf585")]
    FaceGrinSquint,
    [Description("\uf586")]
    FaceGrinSquintTears,
    [Description("\uf587")]
    FaceGrinStars,
    [Description("\uf588")]
    FaceGrinTears,
    [Description("\uf589")]
    FaceGrinTongue,
    [Description("\uf58a")]
    FaceGrinTongueSquint,
    [Description("\uf58b")]
    FaceGrinTongueWink,
    [Description("\uf581")]
    FaceGrinWide,
    [Description("\uf58c")]
    FaceGrinWink,
    [Description("\uf596")]
    FaceKiss,
    [Description("\uf597")]
    FaceKissBeam,
    [Description("\uf598")]
    FaceKissWinkHeart,
    [Description("\uf599")]
    FaceLaugh,
    [Description("\uf59a")]
    FaceLaughBeam,
    [Description("\uf59b")]
    FaceLaughSquint,
    [Description("\uf59c")]
    FaceLaughWink,
    [Description("\uf11a")]
    FaceMeh,
    [Description("\uf5a4")]
    FaceMehBlank,
    [Description("\uf5a5")]
    FaceRollingEyes,
    [Description("\uf5b3")]
    FaceSadCry,
    [Description("\uf5b4")]
    FaceSadTear,
    [Description("\uf118")]
    FaceSmile,
    [Description("\uf5b8")]
    FaceSmileBeam,
    [Description("\uf4da")]
    FaceSmileWink,
    [Description("\uf5c2")]
    FaceSurprise,
    [Description("\uf5c8")]
    FaceTired,
    [Description("\uf863")]
    Fan,
    [Description("\ue005")]
    Faucet,
    [Description("\ue006")]
    FaucetDrip,
    [Description("\uf1ac")]
    Fax,
    [Description("\uf52d")]
    Feather,
    [Description("\uf56b")]
    FeatherPointed,
    [Description("\ue4ea")]
    Ferry,
    [Description("\uf15b")]
    File,
    [Description("\uf56d")]
    FileArrowDown,
    [Description("\uf574")]
    FileArrowUp,
    [Description("\uf1c7")]
    FileAudio,
    [Description("\ue5a0")]
    FileCircleCheck,
    [Description("\ue4eb")]
    FileCircleExclamation,
    [Description("\ue4ed")]
    FileCircleMinus,
    [Description("\ue494")]
    FileCirclePlus,
    [Description("\ue4ef")]
    FileCircleQuestion,
    [Description("\ue5a1")]
    FileCircleXmark,
    [Description("\uf1c9")]
    FileCode,
    [Description("\uf56c")]
    FileContract,
    [Description("\uf6dd")]
    FileCsv,
    [Description("\uf1c3")]
    FileExcel,
    [Description("\uf56e")]
    FileExport,
    [Description("\ue697")]
    FileFragment,
    [Description("\ue698")]
    FileHalfDashed,
    [Description("\uf1c5")]
    FileImage,
    [Description("\uf56f")]
    FileImport,
    [Description("\uf570")]
    FileInvoice,
    [Description("\uf571")]
    FileInvoiceDollar,
    [Description("\uf15c")]
    FileLines,
    [Description("\uf477")]
    FileMedical,
    [Description("\uf1c1")]
    FilePdf,
    [Description("\uf31c")]
    FilePen,
    [Description("\uf1c4")]
    FilePowerpoint,
    [Description("\uf572")]
    FilePrescription,
    [Description("\ue4f0")]
    FileShield,
    [Description("\uf573")]
    FileSignature,
    [Description("\uf1c8")]
    FileVideo,
    [Description("\uf478")]
    FileWaveform,
    [Description("\uf1c2")]
    FileWord,
    [Description("\uf1c6")]
    FileZipper,
    [Description("\uf575")]
    Fill,
    [Description("\uf576")]
    FillDrip,
    [Description("\uf008")]
    Film,
    [Description("\uf0b0")]
    Filter,
    [Description("\uf662")]
    FilterCircleDollar,
    [Description("\ue17b")]
    FilterCircleXmark,
    [Description("\uf577")]
    Fingerprint,
    [Description("\uf06d")]
    Fire,
    [Description("\ue4f1")]
    FireBurner,
    [Description("\uf134")]
    FireExtinguisher,
    [Description("\uf7e4")]
    FireFlameCurved,
    [Description("\uf46a")]
    FireFlameSimple,
    [Description("\uf578")]
    Fish,
    [Description("\ue4f2")]
    FishFins,
    [Description("\uf024")]
    Flag,
    [Description("\uf11e")]
    FlagCheckered,
    [Description("\uf74d")]
    FlagUsa,
    [Description("\uf0c3")]
    Flask,
    [Description("\ue4f3")]
    FlaskVial,
    [Description("\uf0c7")]
    FloppyDisk,
    [Description("\ue184")]
    FlorinSign,
    [Description("\uf07b")]
    Folder,
    [Description("\ue185")]
    FolderClosed,
    [Description("\uf65d")]
    FolderMinus,
    [Description("\uf07c")]
    FolderOpen,
    [Description("\uf65e")]
    FolderPlus,
    [Description("\uf802")]
    FolderTree,
    [Description("\uf031")]
    Font,
    [Description("\uf2b4")]
    FontAwesome,
    [Description("\uf44e")]
    Football,
    [Description("\uf04e")]
    Forward,
    [Description("\uf050")]
    ForwardFast,
    [Description("\uf051")]
    ForwardStep,
    [Description("\ue18f")]
    FrancSign,
    [Description("\uf52e")]
    Frog,
    [Description("\uf1e3")]
    Futbol,
    [Description("\u0047")]
    G,
    [Description("\uf11b")]
    Gamepad,
    [Description("\uf52f")]
    GasPump,
    [Description("\uf624")]
    Gauge,
    [Description("\uf625")]
    GaugeHigh,
    [Description("\uf629")]
    GaugeSimple,
    [Description("\uf62a")]
    GaugeSimpleHigh,
    [Description("\uf0e3")]
    Gavel,
    [Description("\uf013")]
    Gear,
    [Description("\uf085")]
    Gears,
    [Description("\uf3a5")]
    Gem,
    [Description("\ue849")]
    Gemini,
    [Description("\uf22d")]
    Genderless,
    [Description("\uf6e2")]
    Ghost,
    [Description("\uf06b")]
    Gift,
    [Description("\uf79c")]
    Gifts,
    [Description("\ue4f4")]
    GlassWater,
    [Description("\ue4f5")]
    GlassWaterDroplet,
    [Description("\uf530")]
    Glasses,
    [Description("\uf0ac")]
    Globe,
    [Description("\uf450")]
    GolfBallTee,
    [Description("\uf664")]
    Gopuram,
    [Description("\uf19d")]
    GraduationCap,
    [Description("\u003e")]
    GreaterThan,
    [Description("\uf532")]
    GreaterThanEqual,
    [Description("\uf58d")]
    Grip,
    [Description("\uf7a4")]
    GripLines,
    [Description("\uf7a5")]
    GripLinesVertical,
    [Description("\uf58e")]
    GripVertical,
    [Description("\ue4f6")]
    GroupArrowsRotate,
    [Description("\ue19a")]
    GuaraniSign,
    [Description("\uf7a6")]
    Guitar,
    [Description("\ue19b")]
    Gun,
    [Description("\u0048")]
    H,
    [Description("\uf6e3")]
    Hammer,
    [Description("\uf665")]
    Hamsa,
    [Description("\uf256")]
    Hand,
    [Description("\uf255")]
    HandBackFist,
    [Description("\uf461")]
    HandDots,
    [Description("\uf6de")]
    HandFist,
    [Description("\uf4bd")]
    HandHolding,
    [Description("\uf4c0")]
    HandHoldingDollar,
    [Description("\uf4c1")]
    HandHoldingDroplet,
    [Description("\ue4f7")]
    HandHoldingHand,
    [Description("\uf4be")]
    HandHoldingHeart,
    [Description("\ue05c")]
    HandHoldingMedical,
    [Description("\uf258")]
    HandLizard,
    [Description("\uf806")]
    HandMiddleFinger,
    [Description("\uf25b")]
    HandPeace,
    [Description("\uf0a7")]
    HandPointDown,
    [Description("\uf0a5")]
    HandPointLeft,
    [Description("\uf0a4")]
    HandPointRight,
    [Description("\uf0a6")]
    HandPointUp,
    [Description("\uf25a")]
    HandPointer,
    [Description("\uf257")]
    HandScissors,
    [Description("\ue05d")]
    HandSparkles,
    [Description("\uf259")]
    HandSpock,
    [Description("\ue4f8")]
    Handcuffs,
    [Description("\uf2a7")]
    Hands,
    [Description("\uf2a3")]
    HandsAslInterpreting,
    [Description("\ue4f9")]
    HandsBound,
    [Description("\ue05e")]
    HandsBubbles,
    [Description("\ue1a8")]
    HandsClapping,
    [Description("\uf4c2")]
    HandsHolding,
    [Description("\ue4fa")]
    HandsHoldingChild,
    [Description("\ue4fb")]
    HandsHoldingCircle,
    [Description("\uf684")]
    HandsPraying,
    [Description("\uf2b5")]
    Handshake,
    [Description("\uf4c4")]
    HandshakeAngle,
    [Description("\ue060")]
    HandshakeSlash,
    [Description("\uf6e6")]
    Hanukiah,
    [Description("\uf0a0")]
    HardDrive,
    [Description("\u0023")]
    Hashtag,
    [Description("\uf8c0")]
    HatCowboy,
    [Description("\uf8c1")]
    HatCowboySide,
    [Description("\uf6e8")]
    HatWizard,
    [Description("\ue061")]
    HeadSideCough,
    [Description("\ue062")]
    HeadSideCoughSlash,
    [Description("\ue063")]
    HeadSideMask,
    [Description("\ue064")]
    HeadSideVirus,
    [Description("\uf1dc")]
    Heading,
    [Description("\uf025")]
    Headphones,
    [Description("\uf590")]
    Headset,
    [Description("\uf004")]
    Heart,
    [Description("\ue4fc")]
    HeartCircleBolt,
    [Description("\ue4fd")]
    HeartCircleCheck,
    [Description("\ue4fe")]
    HeartCircleExclamation,
    [Description("\ue4ff")]
    HeartCircleMinus,
    [Description("\ue500")]
    HeartCirclePlus,
    [Description("\ue501")]
    HeartCircleXmark,
    [Description("\uf7a9")]
    HeartCrack,
    [Description("\uf21e")]
    HeartPulse,
    [Description("\uf533")]
    Helicopter,
    [Description("\ue502")]
    HelicopterSymbol,
    [Description("\uf807")]
    HelmetSafety,
    [Description("\ue503")]
    HelmetUn,
    [Description("\uf312")]
    Hexagon,
    [Description("\ue699")]
    HexagonNodes,
    [Description("\ue69a")]
    HexagonNodesBolt,
    [Description("\uf591")]
    Highlighter,
    [Description("\ue507")]
    HillAvalanche,
    [Description("\ue508")]
    HillRockslide,
    [Description("\uf6ed")]
    Hippo,
    [Description("\uf453")]
    HockeyPuck,
    [Description("\uf7aa")]
    HollyBerry,
    [Description("\uf6f0")]
    Horse,
    [Description("\uf7ab")]
    HorseHead,
    [Description("\uf0f8")]
    Hospital,
    [Description("\uf80d")]
    HospitalUser,
    [Description("\uf593")]
    HotTubPerson,
    [Description("\uf80f")]
    Hotdog,
    [Description("\uf594")]
    Hotel,
    [Description("\uf254")]
    Hourglass,
    [Description("\uf253")]
    HourglassEnd,
    [Description("\uf252")]
    HourglassHalf,
    [Description("\uf251")]
    HourglassStart,
    [Description("\uf015")]
    House,
    [Description("\ue3af")]
    HouseChimney,
    [Description("\uf6f1")]
    HouseChimneyCrack,
    [Description("\uf7f2")]
    HouseChimneyMedical,
    [Description("\ue065")]
    HouseChimneyUser,
    [Description("\ue00d")]
    HouseChimneyWindow,
    [Description("\ue509")]
    HouseCircleCheck,
    [Description("\ue50a")]
    HouseCircleExclamation,
    [Description("\ue50b")]
    HouseCircleXmark,
    [Description("\ue3b1")]
    HouseCrack,
    [Description("\ue50c")]
    HouseFire,
    [Description("\ue50d")]
    HouseFlag,
    [Description("\ue50e")]
    HouseFloodWater,
    [Description("\ue50f")]
    HouseFloodWaterCircleArrowRight,
    [Description("\ue066")]
    HouseLaptop,
    [Description("\ue510")]
    HouseLock,
    [Description("\ue3b2")]
    HouseMedical,
    [Description("\ue511")]
    HouseMedicalCircleCheck,
    [Description("\ue512")]
    HouseMedicalCircleExclamation,
    [Description("\ue513")]
    HouseMedicalCircleXmark,
    [Description("\ue514")]
    HouseMedicalFlag,
    [Description("\ue012")]
    HouseSignal,
    [Description("\ue515")]
    HouseTsunami,
    [Description("\ue1b0")]
    HouseUser,
    [Description("\uf6f2")]
    HryvniaSign,
    [Description("\uf751")]
    Hurricane,
    [Description("\u0049")]
    I,
    [Description("\uf246")]
    ICursor,
    [Description("\uf810")]
    IceCream,
    [Description("\uf7ad")]
    Icicles,
    [Description("\uf86d")]
    Icons,
    [Description("\uf2c1")]
    IdBadge,
    [Description("\uf2c2")]
    IdCard,
    [Description("\uf47f")]
    IdCardClip,
    [Description("\uf7ae")]
    Igloo,
    [Description("\uf03e")]
    Image,
    [Description("\uf3e0")]
    ImagePortrait,
    [Description("\uf302")]
    Images,
    [Description("\uf01c")]
    Inbox,
    [Description("\uf03c")]
    Indent,
    [Description("\ue1bc")]
    IndianRupeeSign,
    [Description("\uf275")]
    Industry,
    [Description("\uf534")]
    Infinity,
    [Description("\uf129")]
    Info,
    [Description("\uf033")]
    Italic,
    [Description("\u004a")]
    J,
    [Description("\ue516")]
    Jar,
    [Description("\ue517")]
    JarWheat,
    [Description("\uf669")]
    Jedi,
    [Description("\uf0fb")]
    JetFighter,
    [Description("\ue518")]
    JetFighterUp,
    [Description("\uf595")]
    Joint,
    [Description("\ue519")]
    JugDetergent,
    [Description("\u004b")]
    K,
    [Description("\uf66b")]
    Kaaba,
    [Description("\uf084")]
    Key,
    [Description("\uf11c")]
    Keyboard,
    [Description("\uf66d")]
    Khanda,
    [Description("\ue1c4")]
    KipSign,
    [Description("\uf479")]
    KitMedical,
    [Description("\ue51a")]
    KitchenSet,
    [Description("\uf535")]
    KiwiBird,
    [Description("\u004c")]
    L,
    [Description("\ue51b")]
    LandMineOn,
    [Description("\uf66f")]
    Landmark,
    [Description("\uf752")]
    LandmarkDome,
    [Description("\ue51c")]
    LandmarkFlag,
    [Description("\uf1ab")]
    Language,
    [Description("\uf109")]
    Laptop,
    [Description("\uf5fc")]
    LaptopCode,
    [Description("\ue51d")]
    LaptopFile,
    [Description("\uf812")]
    LaptopMedical,
    [Description("\ue1c8")]
    LariSign,
    [Description("\uf5fd")]
    LayerGroup,
    [Description("\uf06c")]
    Leaf,
    [Description("\uf30a")]
    LeftLong,
    [Description("\uf337")]
    LeftRight,
    [Description("\uf094")]
    Lemon,
    [Description("\ue84a")]
    Leo,
    [Description("\u003c")]
    LessThan,
    [Description("\uf537")]
    LessThanEqual,
    [Description("\ue84b")]
    Libra,
    [Description("\uf1cd")]
    LifeRing,
    [Description("\uf0eb")]
    Lightbulb,
    [Description("\ue51e")]
    LinesLeaning,
    [Description("\uf0c1")]
    Link,
    [Description("\uf127")]
    LinkSlash,
    [Description("\uf195")]
    LiraSign,
    [Description("\uf03a")]
    List,
    [Description("\uf0ae")]
    ListCheck,
    [Description("\uf0cb")]
    ListOl,
    [Description("\uf0ca")]
    ListUl,
    [Description("\ue1d3")]
    LitecoinSign,
    [Description("\uf124")]
    LocationArrow,
    [Description("\uf601")]
    LocationCrosshairs,
    [Description("\uf3c5")]
    LocationDot,
    [Description("\uf041")]
    LocationPin,
    [Description("\ue51f")]
    LocationPinLock,
    [Description("\uf023")]
    Lock,
    [Description("\uf3c1")]
    LockOpen,
    [Description("\ue520")]
    Locust,
    [Description("\uf604")]
    Lungs,
    [Description("\ue067")]
    LungsVirus,
    [Description("\u004d")]
    M,
    [Description("\uf076")]
    Magnet,
    [Description("\uf002")]
    MagnifyingGlass,
    [Description("\ue521")]
    MagnifyingGlassArrowRight,
    [Description("\ue522")]
    MagnifyingGlassChart,
    [Description("\uf688")]
    MagnifyingGlassDollar,
    [Description("\uf689")]
    MagnifyingGlassLocation,
    [Description("\uf010")]
    MagnifyingGlassMinus,
    [Description("\uf00e")]
    MagnifyingGlassPlus,
    [Description("\ue1d5")]
    ManatSign,
    [Description("\uf279")]
    Map,
    [Description("\uf59f")]
    MapLocation,
    [Description("\uf5a0")]
    MapLocationDot,
    [Description("\uf276")]
    MapPin,
    [Description("\uf5a1")]
    Marker,
    [Description("\uf222")]
    Mars,
    [Description("\uf224")]
    MarsAndVenus,
    [Description("\ue523")]
    MarsAndVenusBurst,
    [Description("\uf227")]
    MarsDouble,
    [Description("\uf229")]
    MarsStroke,
    [Description("\uf22b")]
    MarsStrokeRight,
    [Description("\uf22a")]
    MarsStrokeUp,
    [Description("\uf57b")]
    MartiniGlass,
    [Description("\uf561")]
    MartiniGlassCitrus,
    [Description("\uf000")]
    MartiniGlassEmpty,
    [Description("\uf6fa")]
    Mask,
    [Description("\ue1d7")]
    MaskFace,
    [Description("\ue524")]
    MaskVentilator,
    [Description("\uf630")]
    MasksTheater,
    [Description("\ue525")]
    MattressPillow,
    [Description("\uf31e")]
    Maximize,
    [Description("\uf5a2")]
    Medal,
    [Description("\uf538")]
    Memory,
    [Description("\uf676")]
    Menorah,
    [Description("\uf223")]
    Mercury,
    [Description("\uf27a")]
    Message,
    [Description("\uf753")]
    Meteor,
    [Description("\uf2db")]
    Microchip,
    [Description("\uf130")]
    Microphone,
    [Description("\uf3c9")]
    MicrophoneLines,
    [Description("\uf539")]
    MicrophoneLinesSlash,
    [Description("\uf131")]
    MicrophoneSlash,
    [Description("\uf610")]
    Microscope,
    [Description("\ue1ed")]
    MillSign,
    [Description("\uf78c")]
    Minimize,
    [Description("\uf068")]
    Minus,
    [Description("\uf7b5")]
    Mitten,
    [Description("\uf3ce")]
    Mobile,
    [Description("\uf10b")]
    MobileButton,
    [Description("\ue527")]
    MobileRetro,
    [Description("\uf3cf")]
    MobileScreen,
    [Description("\uf3cd")]
    MobileScreenButton,
    [Description("\ue816")]
    MobileVibrate,
    [Description("\uf0d6")]
    MoneyBill,
    [Description("\uf3d1")]
    MoneyBill1,
    [Description("\uf53b")]
    MoneyBill1Wave,
    [Description("\ue528")]
    MoneyBillTransfer,
    [Description("\ue529")]
    MoneyBillTrendUp,
    [Description("\uf53a")]
    MoneyBillWave,
    [Description("\ue52a")]
    MoneyBillWheat,
    [Description("\ue1f3")]
    MoneyBills,
    [Description("\uf53c")]
    MoneyCheck,
    [Description("\uf53d")]
    MoneyCheckDollar,
    [Description("\uf5a6")]
    Monument,
    [Description("\uf186")]
    Moon,
    [Description("\uf5a7")]
    MortarPestle,
    [Description("\uf678")]
    Mosque,
    [Description("\ue52b")]
    Mosquito,
    [Description("\ue52c")]
    MosquitoNet,
    [Description("\uf21c")]
    Motorcycle,
    [Description("\ue52d")]
    Mound,
    [Description("\uf6fc")]
    Mountain,
    [Description("\ue52e")]
    MountainCity,
    [Description("\ue52f")]
    MountainSun,
    [Description("\uf7b6")]
    MugHot,
    [Description("\uf0f4")]
    MugSaucer,
    [Description("\uf001")]
    Music,
    [Description("\u004e")]
    N,
    [Description("\ue1f6")]
    NairaSign,
    [Description("\uf6ff")]
    NetworkWired,
    [Description("\uf22c")]
    Neuter,
    [Description("\uf1ea")]
    Newspaper,
    [Description("\ue807")]
    NonBinary,
    [Description("\uf53e")]
    NotEqual,
    [Description("\ue1fe")]
    Notdef,
    [Description("\uf249")]
    NoteSticky,
    [Description("\uf481")]
    NotesMedical,
    [Description("\u004f")]
    O,
    [Description("\uf247")]
    ObjectGroup,
    [Description("\uf248")]
    ObjectUngroup,
    [Description("\uf306")]
    Octagon,
    [Description("\uf613")]
    OilCan,
    [Description("\ue532")]
    OilWell,
    [Description("\uf679")]
    Om,
    [Description("\uf700")]
    Otter,
    [Description("\uf03b")]
    Outdent,
    [Description("\u0050")]
    P,
    [Description("\uf815")]
    Pager,
    [Description("\uf5aa")]
    PaintRoller,
    [Description("\uf1fc")]
    Paintbrush,
    [Description("\uf53f")]
    Palette,
    [Description("\uf482")]
    Pallet,
    [Description("\ue209")]
    Panorama,
    [Description("\uf1d8")]
    PaperPlane,
    [Description("\uf0c6")]
    Paperclip,
    [Description("\uf4cd")]
    ParachuteBox,
    [Description("\uf1dd")]
    Paragraph,
    [Description("\uf5ab")]
    Passport,
    [Description("\uf0ea")]
    Paste,
    [Description("\uf04c")]
    Pause,
    [Description("\uf1b0")]
    Paw,
    [Description("\uf67c")]
    Peace,
    [Description("\uf304")]
    Pen,
    [Description("\uf305")]
    PenClip,
    [Description("\uf5ac")]
    PenFancy,
    [Description("\uf5ad")]
    PenNib,
    [Description("\uf5ae")]
    PenRuler,
    [Description("\uf044")]
    PenToSquare,
    [Description("\uf303")]
    Pencil,
    [Description("\ue790")]
    Pentagon,
    [Description("\ue068")]
    PeopleArrows,
    [Description("\uf4ce")]
    PeopleCarryBox,
    [Description("\ue533")]
    PeopleGroup,
    [Description("\ue534")]
    PeopleLine,
    [Description("\ue535")]
    PeoplePulling,
    [Description("\ue536")]
    PeopleRobbery,
    [Description("\ue537")]
    PeopleRoof,
    [Description("\uf816")]
    PepperHot,
    [Description("\u0025")]
    Percent,
    [Description("\uf183")]
    Person,
    [Description("\ue538")]
    PersonArrowDownToLine,
    [Description("\ue539")]
    PersonArrowUpFromLine,
    [Description("\uf84a")]
    PersonBiking,
    [Description("\uf756")]
    PersonBooth,
    [Description("\ue53a")]
    PersonBreastfeeding,
    [Description("\ue53b")]
    PersonBurst,
    [Description("\ue53c")]
    PersonCane,
    [Description("\ue53d")]
    PersonChalkboard,
    [Description("\ue53e")]
    PersonCircleCheck,
    [Description("\ue53f")]
    PersonCircleExclamation,
    [Description("\ue540")]
    PersonCircleMinus,
    [Description("\ue541")]
    PersonCirclePlus,
    [Description("\ue542")]
    PersonCircleQuestion,
    [Description("\ue543")]
    PersonCircleXmark,
    [Description("\uf85e")]
    PersonDigging,
    [Description("\uf470")]
    PersonDotsFromLine,
    [Description("\uf182")]
    PersonDress,
    [Description("\ue544")]
    PersonDressBurst,
    [Description("\ue545")]
    PersonDrowning,
    [Description("\ue546")]
    PersonFalling,
    [Description("\ue547")]
    PersonFallingBurst,
    [Description("\ue548")]
    PersonHalfDress,
    [Description("\ue549")]
    PersonHarassing,
    [Description("\uf6ec")]
    PersonHiking,
    [Description("\ue54a")]
    PersonMilitaryPointing,
    [Description("\ue54b")]
    PersonMilitaryRifle,
    [Description("\ue54c")]
    PersonMilitaryToPerson,
    [Description("\uf683")]
    PersonPraying,
    [Description("\ue31e")]
    PersonPregnant,
    [Description("\ue54d")]
    PersonRays,
    [Description("\ue54e")]
    PersonRifle,
    [Description("\uf70c")]
    PersonRunning,
    [Description("\ue54f")]
    PersonShelter,
    [Description("\uf7c5")]
    PersonSkating,
    [Description("\uf7c9")]
    PersonSkiing,
    [Description("\uf7ca")]
    PersonSkiingNordic,
    [Description("\uf7ce")]
    PersonSnowboarding,
    [Description("\uf5c4")]
    PersonSwimming,
    [Description("\ue5a9")]
    PersonThroughWindow,
    [Description("\uf554")]
    PersonWalking,
    [Description("\ue551")]
    PersonWalkingArrowLoopLeft,
    [Description("\ue552")]
    PersonWalkingArrowRight,
    [Description("\ue553")]
    PersonWalkingDashedLineArrowRight,
    [Description("\ue554")]
    PersonWalkingLuggage,
    [Description("\uf29d")]
    PersonWalkingWithCane,
    [Description("\ue221")]
    PesetaSign,
    [Description("\ue222")]
    PesoSign,
    [Description("\uf095")]
    Phone,
    [Description("\uf879")]
    PhoneFlip,
    [Description("\uf3dd")]
    PhoneSlash,
    [Description("\uf2a0")]
    PhoneVolume,
    [Description("\uf87c")]
    PhotoFilm,
    [Description("\ue80b")]
    PictureInPicture,
    [Description("\uf4d3")]
    PiggyBank,
    [Description("\uf484")]
    Pills,
    [Description("\ue84c")]
    Pisces,
    [Description("\uf818")]
    PizzaSlice,
    [Description("\uf67f")]
    PlaceOfWorship,
    [Description("\uf072")]
    Plane,
    [Description("\uf5af")]
    PlaneArrival,
    [Description("\ue555")]
    PlaneCircleCheck,
    [Description("\ue556")]
    PlaneCircleExclamation,
    [Description("\ue557")]
    PlaneCircleXmark,
    [Description("\uf5b0")]
    PlaneDeparture,
    [Description("\ue558")]
    PlaneLock,
    [Description("\ue069")]
    PlaneSlash,
    [Description("\ue22d")]
    PlaneUp,
    [Description("\ue5aa")]
    PlantWilt,
    [Description("\ue55a")]
    PlateWheat,
    [Description("\uf04b")]
    Play,
    [Description("\uf1e6")]
    Plug,
    [Description("\ue55b")]
    PlugCircleBolt,
    [Description("\ue55c")]
    PlugCircleCheck,
    [Description("\ue55d")]
    PlugCircleExclamation,
    [Description("\ue55e")]
    PlugCircleMinus,
    [Description("\ue55f")]
    PlugCirclePlus,
    [Description("\ue560")]
    PlugCircleXmark,
    [Description("\u002b")]
    Plus,
    [Description("\ue43c")]
    PlusMinus,
    [Description("\uf2ce")]
    Podcast,
    [Description("\uf2fe")]
    Poo,
    [Description("\uf75a")]
    PooStorm,
    [Description("\uf619")]
    Poop,
    [Description("\uf011")]
    PowerOff,
    [Description("\uf5b1")]
    Prescription,
    [Description("\uf485")]
    PrescriptionBottle,
    [Description("\uf486")]
    PrescriptionBottleMedical,
    [Description("\uf02f")]
    Print,
    [Description("\ue06a")]
    PumpMedical,
    [Description("\ue06b")]
    PumpSoap,
    [Description("\uf12e")]
    PuzzlePiece,
    [Description("\u0051")]
    Q,
    [Description("\uf029")]
    Qrcode,
    [Description("\u003f")]
    Question,
    [Description("\uf10d")]
    QuoteLeft,
    [Description("\uf10e")]
    QuoteRight,
    [Description("\u0052")]
    R,
    [Description("\uf7b9")]
    Radiation,
    [Description("\uf8d7")]
    Radio,
    [Description("\uf75b")]
    Rainbow,
    [Description("\ue561")]
    RankingStar,
    [Description("\uf543")]
    Receipt,
    [Description("\uf8d9")]
    RecordVinyl,
    [Description("\uf641")]
    RectangleAd,
    [Description("\uf022")]
    RectangleList,
    [Description("\uf410")]
    RectangleXmark,
    [Description("\uf1b8")]
    Recycle,
    [Description("\uf25d")]
    Registered,
    [Description("\uf363")]
    Repeat,
    [Description("\uf3e5")]
    Reply,
    [Description("\uf122")]
    ReplyAll,
    [Description("\uf75e")]
    Republican,
    [Description("\uf7bd")]
    Restroom,
    [Description("\uf079")]
    Retweet,
    [Description("\uf4d6")]
    Ribbon,
    [Description("\uf2f5")]
    RightFromBracket,
    [Description("\uf362")]
    RightLeft,
    [Description("\uf30b")]
    RightLong,
    [Description("\uf2f6")]
    RightToBracket,
    [Description("\uf70b")]
    Ring,
    [Description("\uf018")]
    Road,
    [Description("\ue562")]
    RoadBarrier,
    [Description("\ue563")]
    RoadBridge,
    [Description("\ue564")]
    RoadCircleCheck,
    [Description("\ue565")]
    RoadCircleExclamation,
    [Description("\ue566")]
    RoadCircleXmark,
    [Description("\ue567")]
    RoadLock,
    [Description("\ue568")]
    RoadSpikes,
    [Description("\uf544")]
    Robot,
    [Description("\uf135")]
    Rocket,
    [Description("\uf2f1")]
    Rotate,
    [Description("\uf2ea")]
    RotateLeft,
    [Description("\uf2f9")]
    RotateRight,
    [Description("\uf4d7")]
    Route,
    [Description("\uf09e")]
    Rss,
    [Description("\uf158")]
    RubleSign,
    [Description("\ue569")]
    Rug,
    [Description("\uf545")]
    Ruler,
    [Description("\uf546")]
    RulerCombined,
    [Description("\uf547")]
    RulerHorizontal,
    [Description("\uf548")]
    RulerVertical,
    [Description("\uf156")]
    RupeeSign,
    [Description("\ue23d")]
    RupiahSign,
    [Description("\u0053")]
    S,
    [Description("\uf81d")]
    SackDollar,
    [Description("\ue56a")]
    SackXmark,
    [Description("\ue84d")]
    Sagittarius,
    [Description("\ue445")]
    Sailboat,
    [Description("\uf7bf")]
    Satellite,
    [Description("\uf7c0")]
    SatelliteDish,
    [Description("\uf24e")]
    ScaleBalanced,
    [Description("\uf515")]
    ScaleUnbalanced,
    [Description("\uf516")]
    ScaleUnbalancedFlip,
    [Description("\uf549")]
    School,
    [Description("\ue56b")]
    SchoolCircleCheck,
    [Description("\ue56c")]
    SchoolCircleExclamation,
    [Description("\ue56d")]
    SchoolCircleXmark,
    [Description("\ue56e")]
    SchoolFlag,
    [Description("\ue56f")]
    SchoolLock,
    [Description("\uf0c4")]
    Scissors,
    [Description("\ue84e")]
    Scorpio,
    [Description("\uf54a")]
    Screwdriver,
    [Description("\uf7d9")]
    ScrewdriverWrench,
    [Description("\uf70e")]
    Scroll,
    [Description("\uf6a0")]
    ScrollTorah,
    [Description("\uf7c2")]
    SdCard,
    [Description("\ue447")]
    Section,
    [Description("\uf4d8")]
    Seedling,
    [Description("\ue820")]
    Septagon,
    [Description("\uf233")]
    Server,
    [Description("\uf61f")]
    Shapes,
    [Description("\uf064")]
    Share,
    [Description("\uf14d")]
    ShareFromSquare,
    [Description("\uf1e0")]
    ShareNodes,
    [Description("\ue571")]
    SheetPlastic,
    [Description("\uf20b")]
    ShekelSign,
    [Description("\uf132")]
    Shield,
    [Description("\ue572")]
    ShieldCat,
    [Description("\ue573")]
    ShieldDog,
    [Description("\uf3ed")]
    ShieldHalved,
    [Description("\ue574")]
    ShieldHeart,
    [Description("\ue06c")]
    ShieldVirus,
    [Description("\uf21a")]
    Ship,
    [Description("\uf553")]
    Shirt,
    [Description("\uf54b")]
    ShoePrints,
    [Description("\uf54f")]
    Shop,
    [Description("\ue4a5")]
    ShopLock,
    [Description("\ue070")]
    ShopSlash,
    [Description("\uf2cc")]
    Shower,
    [Description("\ue448")]
    Shrimp,
    [Description("\uf074")]
    Shuffle,
    [Description("\uf197")]
    ShuttleSpace,
    [Description("\uf4d9")]
    SignHanging,
    [Description("\uf012")]
    Signal,
    [Description("\uf5b7")]
    Signature,
    [Description("\uf277")]
    SignsPost,
    [Description("\uf7c4")]
    SimCard,
    [Description("\ue81b")]
    SingleQuoteLeft,
    [Description("\ue81c")]
    SingleQuoteRight,
    [Description("\ue06d")]
    Sink,
    [Description("\uf0e8")]
    Sitemap,
    [Description("\uf54c")]
    Skull,
    [Description("\uf714")]
    SkullCrossbones,
    [Description("\uf715")]
    Slash,
    [Description("\uf7cc")]
    Sleigh,
    [Description("\uf1de")]
    Sliders,
    [Description("\uf75f")]
    Smog,
    [Description("\uf48d")]
    Smoking,
    [Description("\uf2dc")]
    Snowflake,
    [Description("\uf7d0")]
    Snowman,
    [Description("\uf7d2")]
    Snowplow,
    [Description("\ue06e")]
    Soap,
    [Description("\uf696")]
    Socks,
    [Description("\uf5ba")]
    SolarPanel,
    [Description("\uf0dc")]
    Sort,
    [Description("\uf0dd")]
    SortDown,
    [Description("\uf0de")]
    SortUp,
    [Description("\uf5bb")]
    Spa,
    [Description("\uf67b")]
    SpaghettiMonsterFlying,
    [Description("\uf891")]
    SpellCheck,
    [Description("\uf717")]
    Spider,
    [Description("\uf110")]
    Spinner,
    [Description("\ue80a")]
    Spiral,
    [Description("\uf5bc")]
    Splotch,
    [Description("\uf2e5")]
    Spoon,
    [Description("\uf5bd")]
    SprayCan,
    [Description("\uf5d0")]
    SprayCanSparkles,
    [Description("\uf0c8")]
    Square,
    [Description("\uf14c")]
    SquareArrowUpRight,
    [Description("\ue69b")]
    SquareBinary,
    [Description("\uf150")]
    SquareCaretDown,
    [Description("\uf191")]
    SquareCaretLeft,
    [Description("\uf152")]
    SquareCaretRight,
    [Description("\uf151")]
    SquareCaretUp,
    [Description("\uf14a")]
    SquareCheck,
    [Description("\uf199")]
    SquareEnvelope,
    [Description("\uf45c")]
    SquareFull,
    [Description("\uf0fd")]
    SquareH,
    [Description("\uf146")]
    SquareMinus,
    [Description("\ue576")]
    SquareNfi,
    [Description("\uf540")]
    SquareParking,
    [Description("\uf14b")]
    SquarePen,
    [Description("\ue577")]
    SquarePersonConfined,
    [Description("\uf098")]
    SquarePhone,
    [Description("\uf87b")]
    SquarePhoneFlip,
    [Description("\uf0fe")]
    SquarePlus,
    [Description("\uf682")]
    SquarePollHorizontal,
    [Description("\uf681")]
    SquarePollVertical,
    [Description("\uf698")]
    SquareRootVariable,
    [Description("\uf143")]
    SquareRss,
    [Description("\uf1e1")]
    SquareShareNodes,
    [Description("\uf360")]
    SquareUpRight,
    [Description("\ue578")]
    SquareVirus,
    [Description("\uf2d3")]
    SquareXmark,
    [Description("\ue579")]
    StaffSnake,
    [Description("\ue289")]
    Stairs,
    [Description("\uf5bf")]
    Stamp,
    [Description("\ue5af")]
    Stapler,
    [Description("\uf005")]
    Star,
    [Description("\uf699")]
    StarAndCrescent,
    [Description("\uf089")]
    StarHalf,
    [Description("\uf5c0")]
    StarHalfStroke,
    [Description("\uf69a")]
    StarOfDavid,
    [Description("\uf621")]
    StarOfLife,
    [Description("\uf154")]
    SterlingSign,
    [Description("\uf0f1")]
    Stethoscope,
    [Description("\uf04d")]
    Stop,
    [Description("\uf2f2")]
    Stopwatch,
    [Description("\ue06f")]
    Stopwatch20,
    [Description("\uf54e")]
    Store,
    [Description("\ue071")]
    StoreSlash,
    [Description("\uf21d")]
    StreetView,
    [Description("\uf0cc")]
    Strikethrough,
    [Description("\uf551")]
    Stroopwafel,
    [Description("\uf12c")]
    Subscript,
    [Description("\uf0f2")]
    Suitcase,
    [Description("\uf0fa")]
    SuitcaseMedical,
    [Description("\uf5c1")]
    SuitcaseRolling,
    [Description("\uf185")]
    Sun,
    [Description("\ue57a")]
    SunPlantWilt,
    [Description("\uf12b")]
    Superscript,
    [Description("\uf5c3")]
    Swatchbook,
    [Description("\uf69b")]
    Synagogue,
    [Description("\uf48e")]
    Syringe,
    [Description("\u0054")]
    T,
    [Description("\uf0ce")]
    Table,
    [Description("\uf00a")]
    TableCells,
    [Description("\ue678")]
    TableCellsColumnLock,
    [Description("\uf009")]
    TableCellsLarge,
    [Description("\ue67a")]
    TableCellsRowLock,
    [Description("\ue691")]
    TableCellsRowUnlock,
    [Description("\uf0db")]
    TableColumns,
    [Description("\uf00b")]
    TableList,
    [Description("\uf45d")]
    TableTennisPaddleBall,
    [Description("\uf3fb")]
    Tablet,
    [Description("\uf10a")]
    TabletButton,
    [Description("\uf3fa")]
    TabletScreenButton,
    [Description("\uf490")]
    Tablets,
    [Description("\uf566")]
    TachographDigital,
    [Description("\uf02b")]
    Tag,
    [Description("\uf02c")]
    Tags,
    [Description("\uf4db")]
    Tape,
    [Description("\ue57b")]
    Tarp,
    [Description("\ue57c")]
    TarpDroplet,
    [Description("\ue84f")]
    Taurus,
    [Description("\uf1ba")]
    Taxi,
    [Description("\uf62e")]
    Teeth,
    [Description("\uf62f")]
    TeethOpen,
    [Description("\ue03f")]
    TemperatureArrowDown,
    [Description("\ue040")]
    TemperatureArrowUp,
    [Description("\uf2cb")]
    TemperatureEmpty,
    [Description("\uf2c7")]
    TemperatureFull,
    [Description("\uf2c9")]
    TemperatureHalf,
    [Description("\uf769")]
    TemperatureHigh,
    [Description("\uf76b")]
    TemperatureLow,
    [Description("\uf2ca")]
    TemperatureQuarter,
    [Description("\uf2c8")]
    TemperatureThreeQuarters,
    [Description("\uf7d7")]
    TengeSign,
    [Description("\ue57d")]
    Tent,
    [Description("\ue57e")]
    TentArrowDownToLine,
    [Description("\ue57f")]
    TentArrowLeftRight,
    [Description("\ue580")]
    TentArrowTurnLeft,
    [Description("\ue581")]
    TentArrowsDown,
    [Description("\ue582")]
    Tents,
    [Description("\uf120")]
    Terminal,
    [Description("\uf034")]
    TextHeight,
    [Description("\uf87d")]
    TextSlash,
    [Description("\uf035")]
    TextWidth,
    [Description("\uf491")]
    Thermometer,
    [Description("\uf165")]
    ThumbsDown,
    [Description("\uf164")]
    ThumbsUp,
    [Description("\uf08d")]
    Thumbtack,
    [Description("\ue68f")]
    ThumbtackSlash,
    [Description("\uf145")]
    Ticket,
    [Description("\uf3ff")]
    TicketSimple,
    [Description("\ue29c")]
    Timeline,
    [Description("\uf204")]
    ToggleOff,
    [Description("\uf205")]
    ToggleOn,
    [Description("\uf7d8")]
    Toilet,
    [Description("\uf71e")]
    ToiletPaper,
    [Description("\ue072")]
    ToiletPaperSlash,
    [Description("\ue583")]
    ToiletPortable,
    [Description("\ue584")]
    ToiletsPortable,
    [Description("\uf552")]
    Toolbox,
    [Description("\uf5c9")]
    Tooth,
    [Description("\uf6a1")]
    ToriiGate,
    [Description("\uf76f")]
    Tornado,
    [Description("\uf519")]
    TowerBroadcast,
    [Description("\ue585")]
    TowerCell,
    [Description("\ue586")]
    TowerObservation,
    [Description("\uf722")]
    Tractor,
    [Description("\uf25c")]
    Trademark,
    [Description("\uf637")]
    TrafficLight,
    [Description("\ue041")]
    Trailer,
    [Description("\uf238")]
    Train,
    [Description("\uf239")]
    TrainSubway,
    [Description("\ue5b4")]
    TrainTram,
    [Description("\uf225")]
    Transgender,
    [Description("\uf1f8")]
    Trash,
    [Description("\uf829")]
    TrashArrowUp,
    [Description("\uf2ed")]
    TrashCan,
    [Description("\uf82a")]
    TrashCanArrowUp,
    [Description("\uf1bb")]
    Tree,
    [Description("\ue587")]
    TreeCity,
    [Description("\uf071")]
    TriangleExclamation,
    [Description("\uf091")]
    Trophy,
    [Description("\ue589")]
    Trowel,
    [Description("\ue58a")]
    TrowelBricks,
    [Description("\uf0d1")]
    Truck,
    [Description("\ue58b")]
    TruckArrowRight,
    [Description("\ue58c")]
    TruckDroplet,
    [Description("\uf48b")]
    TruckFast,
    [Description("\ue58d")]
    TruckField,
    [Description("\ue58e")]
    TruckFieldUn,
    [Description("\ue2b7")]
    TruckFront,
    [Description("\uf0f9")]
    TruckMedical,
    [Description("\uf63b")]
    TruckMonster,
    [Description("\uf4df")]
    TruckMoving,
    [Description("\uf63c")]
    TruckPickup,
    [Description("\ue58f")]
    TruckPlane,
    [Description("\uf4de")]
    TruckRampBox,
    [Description("\uf1e4")]
    Tty,
    [Description("\ue2bb")]
    TurkishLiraSign,
    [Description("\uf3be")]
    TurnDown,
    [Description("\uf3bf")]
    TurnUp,
    [Description("\uf26c")]
    Tv,
    [Description("\u0055")]
    U,
    [Description("\uf0e9")]
    Umbrella,
    [Description("\uf5ca")]
    UmbrellaBeach,
    [Description("\uf0cd")]
    Underline,
    [Description("\uf29a")]
    UniversalAccess,
    [Description("\uf09c")]
    Unlock,
    [Description("\uf13e")]
    UnlockKeyhole,
    [Description("\uf338")]
    UpDown,
    [Description("\uf0b2")]
    UpDownLeftRight,
    [Description("\uf30c")]
    UpLong,
    [Description("\uf424")]
    UpRightAndDownLeftFromCenter,
    [Description("\uf35d")]
    UpRightFromSquare,
    [Description("\uf093")]
    Upload,
    [Description("\uf007")]
    User,
    [Description("\uf4fb")]
    UserAstronaut,
    [Description("\uf4fc")]
    UserCheck,
    [Description("\uf4fd")]
    UserClock,
    [Description("\uf0f0")]
    UserDoctor,
    [Description("\uf4fe")]
    UserGear,
    [Description("\uf501")]
    UserGraduate,
    [Description("\uf500")]
    UserGroup,
    [Description("\uf728")]
    UserInjured,
    [Description("\uf502")]
    UserLock,
    [Description("\uf503")]
    UserMinus,
    [Description("\uf504")]
    UserNinja,
    [Description("\uf82f")]
    UserNurse,
    [Description("\uf4ff")]
    UserPen,
    [Description("\uf234")]
    UserPlus,
    [Description("\uf21b")]
    UserSecret,
    [Description("\uf505")]
    UserShield,
    [Description("\uf506")]
    UserSlash,
    [Description("\uf507")]
    UserTag,
    [Description("\uf508")]
    UserTie,
    [Description("\uf235")]
    UserXmark,
    [Description("\uf0c0")]
    Users,
    [Description("\ue591")]
    UsersBetweenLines,
    [Description("\uf509")]
    UsersGear,
    [Description("\ue592")]
    UsersLine,
    [Description("\ue593")]
    UsersRays,
    [Description("\ue594")]
    UsersRectangle,
    [Description("\ue073")]
    UsersSlash,
    [Description("\ue595")]
    UsersViewfinder,
    [Description("\uf2e7")]
    Utensils,
    [Description("\u0056")]
    V,
    [Description("\uf5b6")]
    VanShuttle,
    [Description("\ue2c5")]
    Vault,
    [Description("\uf221")]
    Venus,
    [Description("\uf226")]
    VenusDouble,
    [Description("\uf228")]
    VenusMars,
    [Description("\ue085")]
    Vest,
    [Description("\ue086")]
    VestPatches,
    [Description("\uf492")]
    Vial,
    [Description("\ue596")]
    VialCircleCheck,
    [Description("\ue597")]
    VialVirus,
    [Description("\uf493")]
    Vials,
    [Description("\uf03d")]
    Video,
    [Description("\uf4e2")]
    VideoSlash,
    [Description("\uf6a7")]
    Vihara,
    [Description("\ue850")]
    Virgo,
    [Description("\ue074")]
    Virus,
    [Description("\ue4a8")]
    VirusCovid,
    [Description("\ue4a9")]
    VirusCovidSlash,
    [Description("\ue075")]
    VirusSlash,
    [Description("\ue076")]
    Viruses,
    [Description("\uf897")]
    Voicemail,
    [Description("\uf770")]
    Volcano,
    [Description("\uf45f")]
    Volleyball,
    [Description("\uf6a8")]
    Volume,
    [Description("\uf028")]
    VolumeHigh,
    [Description("\uf027")]
    VolumeLow,
    [Description("\uf026")]
    VolumeOff,
    [Description("\uf6a9")]
    VolumeXmark,
    [Description("\uf729")]
    VrCardboard,
    [Description("\u0057")]
    W,
    [Description("\uf8ef")]
    WalkieTalkie,
    [Description("\uf555")]
    Wallet,
    [Description("\uf0d0")]
    WandMagic,
    [Description("\ue2ca")]
    WandMagicSparkles,
    [Description("\uf72b")]
    WandSparkles,
    [Description("\uf494")]
    Warehouse,
    [Description("\uf773")]
    Water,
    [Description("\uf5c5")]
    WaterLadder,
    [Description("\uf83e")]
    WaveSquare,
    [Description("\ue682")]
    WebAwesome,
    [Description("\uf5cd")]
    WeightHanging,
    [Description("\uf496")]
    WeightScale,
    [Description("\ue2cd")]
    WheatAwn,
    [Description("\ue598")]
    WheatAwnCircleExclamation,
    [Description("\uf193")]
    Wheelchair,
    [Description("\ue2ce")]
    WheelchairMove,
    [Description("\uf7a0")]
    WhiskeyGlass,
    [Description("\uf1eb")]
    Wifi,
    [Description("\uf72e")]
    Wind,
    [Description("\uf2d0")]
    WindowMaximize,
    [Description("\uf2d1")]
    WindowMinimize,
    [Description("\uf2d2")]
    WindowRestore,
    [Description("\uf72f")]
    WineBottle,
    [Description("\uf4e3")]
    WineGlass,
    [Description("\uf5ce")]
    WineGlassEmpty,
    [Description("\uf159")]
    WonSign,
    [Description("\ue599")]
    Worm,
    [Description("\uf0ad")]
    Wrench,
    [Description("\u0058")]
    X,
    [Description("\uf497")]
    XRay,
    [Description("\uf00d")]
    Xmark,
    [Description("\ue59a")]
    XmarksLines,
    [Description("\u0059")]
    Y,
    [Description("\uf157")]
    YenSign,
    [Description("\uf6ad")]
    YinYang,
    [Description("\u005a")]
    Z,
}
