<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetVersion);$(NetVersion)-android</TargetFrameworks>
    <TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);$(NetVersion)-ios;$(NetVersion)-maccatalyst</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);$(NetVersion)-windows10.0.19041.0</TargetFrameworks>

    <SingleProject>true</SingleProject>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>IgrisModz.MauiIcons.Core</PackageId>
    <GitInfoReportImportance>high</GitInfoReportImportance>
    <Summary>Core Library for Maui Icons</Summary>
    <PackageTags>FontAwesome,Material,Maui,Icon,Dotnet,Icons,MauiIcons,iOSIcon,AndroidIcon,MacIcon,WindowsIcon,IgrisModz</PackageTags>
    <Authors>IgrisModz</Authors>
    <Owners>IgrisModz</Owners>
    <NeutralLanguage>en</NeutralLanguage>
    <Product>IgrisModz.MauiIcons.Core ($(NetVersion))</Product>
    <Copyright>© IgrisModz. All rights reserved.</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/IgrisModz/MauiIcons</PackageProjectUrl>
    <RepositoryUrl>https://github.com/IgrisModz/MauiIcons</RepositoryUrl>
    <PackageReleaseNotes>See https://github.com/IgrisModz/MauiIcons/releases</PackageReleaseNotes>
    <DefineConstants>$(DefineConstants);</DefineConstants>
    <UseFullSemVerForNuGet>false</UseFullSemVerForNuGet>
    <Title>IgrisModz.MauiIcons.Core</Title>
    <Description>Core Library for .NET MAUI Icons</Description>
    <PackageIcon>icon.png</PackageIcon>
    <Product>$(AssemblyName) ($(TargetFramework))</Product>
    <Version>1.0.0</Version>
    <PackageVersion>$(Version)$(VersionSuffix)</PackageVersion>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\build\nuget.png" PackagePath="icon.png" Pack="true" />
    <None Include="ReadMe.txt" pack="true" PackagePath="." />
  </ItemGroup>

</Project>
