using System.ComponentModel;

namespace MauiIcons.FontAwesome.Regular;

public enum FontAwesomeRegularIcons
{
    [Description("\uf2b9")]
    AddressBook,
    [Description("\uf2bb")]
    AddressCard,
    [Description("\uf34e")]
    AlarmClock,
    [Description("\uf0f3")]
    Bell,
    [Description("\uf1f6")]
    BellSlash,
    [Description("\uf02e")]
    Bookmark,
    [Description("\uf1ad")]
    Building,
    [Description("\uf133")]
    Calendar,
    [Description("\uf274")]
    CalendarCheck,
    [Description("\uf073")]
    CalendarDays,
    [Description("\uf272")]
    CalendarMinus,
    [Description("\uf271")]
    CalendarPlus,
    [Description("\uf273")]
    CalendarXmark,
    [Description("\uf030")]
    Camera,
    [Description("\uf080")]
    ChartBar,
    [Description("\uf43a")]
    ChessBishop,
    [Description("\uf43f")]
    ChessKing,
    [Description("\uf441")]
    ChessKnight,
    [Description("\uf443")]
    ChessPawn,
    [Description("\uf445")]
    ChessQueen,
    [Description("\uf447")]
    ChessRook,
    [Description("\uf111")]
    Circle,
    [Description("\uf058")]
    CircleCheck,
    [Description("\uf192")]
    CircleDot,
    [Description("\uf358")]
    CircleDown,
    [Description("\uf359")]
    CircleLeft,
    [Description("\uf28b")]
    CirclePause,
    [Description("\uf144")]
    CirclePlay,
    [Description("\uf059")]
    CircleQuestion,
    [Description("\uf35a")]
    CircleRight,
    [Description("\uf28d")]
    CircleStop,
    [Description("\uf35b")]
    CircleUp,
    [Description("\uf2bd")]
    CircleUser,
    [Description("\uf057")]
    CircleXmark,
    [Description("\uf328")]
    Clipboard,
    [Description("\uf017")]
    Clock,
    [Description("\uf24d")]
    Clone,
    [Description("\uf20a")]
    ClosedCaptioning,
    [Description("\uf0c2")]
    Cloud,
    [Description("\uf075")]
    Comment,
    [Description("\uf4ad")]
    CommentDots,
    [Description("\uf086")]
    Comments,
    [Description("\uf14e")]
    Compass,
    [Description("\uf0c5")]
    Copy,
    [Description("\uf1f9")]
    Copyright,
    [Description("\uf09d")]
    CreditCard,
    [Description("\uf0e0")]
    Envelope,
    [Description("\uf2b6")]
    EnvelopeOpen,
    [Description("\uf06e")]
    Eye,
    [Description("\uf070")]
    EyeSlash,
    [Description("\uf556")]
    FaceAngry,
    [Description("\uf567")]
    FaceDizzy,
    [Description("\uf579")]
    FaceFlushed,
    [Description("\uf119")]
    FaceFrown,
    [Description("\uf57a")]
    FaceFrownOpen,
    [Description("\uf57f")]
    FaceGrimace,
    [Description("\uf580")]
    FaceGrin,
    [Description("\uf582")]
    FaceGrinBeam,
    [Description("\uf583")]
    FaceGrinBeamSweat,
    [Description("\uf584")]
    FaceGrinHearts,
    [Description("\uf585")]
    FaceGrinSquint,
    [Description("\uf586")]
    FaceGrinSquintTears,
    [Description("\uf587")]
    FaceGrinStars,
    [Description("\uf588")]
    FaceGrinTears,
    [Description("\uf589")]
    FaceGrinTongue,
    [Description("\uf58a")]
    FaceGrinTongueSquint,
    [Description("\uf58b")]
    FaceGrinTongueWink,
    [Description("\uf581")]
    FaceGrinWide,
    [Description("\uf58c")]
    FaceGrinWink,
    [Description("\uf596")]
    FaceKiss,
    [Description("\uf597")]
    FaceKissBeam,
    [Description("\uf598")]
    FaceKissWinkHeart,
    [Description("\uf599")]
    FaceLaugh,
    [Description("\uf59a")]
    FaceLaughBeam,
    [Description("\uf59b")]
    FaceLaughSquint,
    [Description("\uf59c")]
    FaceLaughWink,
    [Description("\uf11a")]
    FaceMeh,
    [Description("\uf5a4")]
    FaceMehBlank,
    [Description("\uf5a5")]
    FaceRollingEyes,
    [Description("\uf5b3")]
    FaceSadCry,
    [Description("\uf5b4")]
    FaceSadTear,
    [Description("\uf118")]
    FaceSmile,
    [Description("\uf5b8")]
    FaceSmileBeam,
    [Description("\uf4da")]
    FaceSmileWink,
    [Description("\uf5c2")]
    FaceSurprise,
    [Description("\uf5c8")]
    FaceTired,
    [Description("\uf15b")]
    File,
    [Description("\uf1c7")]
    FileAudio,
    [Description("\uf1c9")]
    FileCode,
    [Description("\uf1c3")]
    FileExcel,
    [Description("\uf1c5")]
    FileImage,
    [Description("\uf15c")]
    FileLines,
    [Description("\uf1c1")]
    FilePdf,
    [Description("\uf1c4")]
    FilePowerpoint,
    [Description("\uf1c8")]
    FileVideo,
    [Description("\uf1c2")]
    FileWord,
    [Description("\uf1c6")]
    FileZipper,
    [Description("\uf024")]
    Flag,
    [Description("\uf0c7")]
    FloppyDisk,
    [Description("\uf07b")]
    Folder,
    [Description("\ue185")]
    FolderClosed,
    [Description("\uf07c")]
    FolderOpen,
    [Description("\uf2b4")]
    FontAwesome,
    [Description("\uf1e3")]
    Futbol,
    [Description("\uf3a5")]
    Gem,
    [Description("\uf256")]
    Hand,
    [Description("\uf255")]
    HandBackFist,
    [Description("\uf258")]
    HandLizard,
    [Description("\uf25b")]
    HandPeace,
    [Description("\uf0a7")]
    HandPointDown,
    [Description("\uf0a5")]
    HandPointLeft,
    [Description("\uf0a4")]
    HandPointRight,
    [Description("\uf0a6")]
    HandPointUp,
    [Description("\uf25a")]
    HandPointer,
    [Description("\uf257")]
    HandScissors,
    [Description("\uf259")]
    HandSpock,
    [Description("\uf2b5")]
    Handshake,
    [Description("\uf0a0")]
    HardDrive,
    [Description("\uf025")]
    Headphones,
    [Description("\uf004")]
    Heart,
    [Description("\uf0f8")]
    Hospital,
    [Description("\uf254")]
    Hourglass,
    [Description("\uf252")]
    HourglassHalf,
    [Description("\uf015")]
    House,
    [Description("\uf2c1")]
    IdBadge,
    [Description("\uf2c2")]
    IdCard,
    [Description("\uf03e")]
    Image,
    [Description("\uf302")]
    Images,
    [Description("\uf11c")]
    Keyboard,
    [Description("\uf094")]
    Lemon,
    [Description("\uf1cd")]
    LifeRing,
    [Description("\uf0eb")]
    Lightbulb,
    [Description("\uf279")]
    Map,
    [Description("\uf27a")]
    Message,
    [Description("\uf3d1")]
    MoneyBill1,
    [Description("\uf186")]
    Moon,
    [Description("\uf1ea")]
    Newspaper,
    [Description("\uf249")]
    NoteSticky,
    [Description("\uf247")]
    ObjectGroup,
    [Description("\uf248")]
    ObjectUngroup,
    [Description("\uf1d8")]
    PaperPlane,
    [Description("\uf0ea")]
    Paste,
    [Description("\uf044")]
    PenToSquare,
    [Description("\uf022")]
    RectangleList,
    [Description("\uf410")]
    RectangleXmark,
    [Description("\uf25d")]
    Registered,
    [Description("\uf14d")]
    ShareFromSquare,
    [Description("\uf2dc")]
    Snowflake,
    [Description("\uf0c8")]
    Square,
    [Description("\uf150")]
    SquareCaretDown,
    [Description("\uf191")]
    SquareCaretLeft,
    [Description("\uf152")]
    SquareCaretRight,
    [Description("\uf151")]
    SquareCaretUp,
    [Description("\uf14a")]
    SquareCheck,
    [Description("\uf45c")]
    SquareFull,
    [Description("\uf146")]
    SquareMinus,
    [Description("\uf0fe")]
    SquarePlus,
    [Description("\uf005")]
    Star,
    [Description("\uf089")]
    StarHalf,
    [Description("\uf5c0")]
    StarHalfStroke,
    [Description("\uf185")]
    Sun,
    [Description("\uf165")]
    ThumbsDown,
    [Description("\uf164")]
    ThumbsUp,
    [Description("\uf2ed")]
    TrashCan,
    [Description("\uf0d1")]
    Truck,
    [Description("\uf007")]
    User,
    [Description("\uf2d0")]
    WindowMaximize,
    [Description("\uf2d1")]
    WindowMinimize,
    [Description("\uf2d2")]
    WindowRestore,
}
